-- Hero slideshow admin fields
ALTER TABLE "HeroSlider" ADD COLUMN IF NOT EXISTS "headline" TEXT;
ALTER TABLE "HeroSlider" ADD COLUMN IF NOT EXISTS "description" TEXT;
ALTER TABLE "HeroSlider" ADD COLUMN IF NOT EXISTS "ctaLabel" TEXT DEFAULT 'Shop Now';
ALTER TABLE "HeroSlider" ADD COLUMN IF NOT EXISTS "sortOrder" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "HeroBanner" ADD COLUMN IF NOT EXISTS "ctaLabel" TEXT DEFAULT 'View Deal';
ALTER TABLE "HeroBanner" ADD COLUMN IF NOT EXISTS "sortOrder" INTEGER NOT NULL DEFAULT 0;
